### ISSUE TITLE
Saving once closes the preview, saving again opens it again

### ISSUE THREAD

**Issue by gdavalos** [mjmlio/atom-mjml-preview#15]
This problem began recently so it might be because of some recent atom update.

Steps to reproduce:

1. Open a mjml file and open the preview
1. Make some changes and save, this will close the preview
1. Save again and the preview will open again

**Comment by RDumais** [comment]
I am having the same issue.

**Comment by ngarnier** [comment]
Hi, thanks for reporting the issue @gdavalos & @RDumais, I could reproduce. I did not notice it initially as I had disabled the auto-preview on save.

Indeed it must be related to an Atom update... we'll have to dig into it.

**Comment by eek4ever** [comment]
@ngarnier, Hi!
I have the same problem. Please fix it

**Comment by ngarnier** [comment]
hey @eek4ever, we've got a lot going on with MJML 4 in the pipe. Any help with this issue would be appreciated, feel free to look into it and share anything you find!

**Comment by ngarnier** [comment]
This is fixed in the latest version of the package.

**Comment by eek4ever** [comment]
Thank you, man! Your product is awesome!
