### ISSUE TITLE
Image caching issue

### ISSUE THREAD

**Issue by andreaskoscinski** [mjmlio/atom-mjml-preview#16]
Hi,
I face a problem with the image cache. I use images from https://s3.eu-central-1.amazonaws.com
when I changed the images on s3 the mjml-preview still show the old images. I can't find a way to clear cache or force to re-load the new images from s3.

![image](https://user-images.githubusercontent.com/28729610/34251918-f3b73220-e641-11e7-9a0f-9fac077cc05d.png)

Best regards
Andreas

**Comment by ngarnier** [comment]
Sorry for the late reply @andreaskoscinski, but seems more like a general issue with Atom. Have a look at this comment from the markdown-preview package, the workaround should work too: https://github.com/atom/markdown-preview/issues/207#issuecomment-248848108
