### ISSUE TITLE
Preview is blank (MacOS High Sierra)

### ISSUE THREAD

**Issue by Thomo120** [mjmlio/atom-mjml-preview#21]
I just moved from Windows -> Mac and the Preview Pane is blank but on Windows, it's working with the same code on Atom. I have tried reinstalling and still doesn't want to work, please help!

**Comment by jricaldi** [comment]
it's didn't work in Ubuntu 16.04 atom 1.23.2

![image](https://user-images.githubusercontent.com/2177405/42842198-1ef1e44c-89d2-11e8-8cb3-876207377832.png)

**Comment by jricaldi** [comment]
![image](https://user-images.githubusercontent.com/2177405/42842284-6156bae2-89d2-11e8-9c23-73357f23f6a0.png)

**Comment by iRyusa** [comment]
Mjml 4.1 has an issue with migrating old file please migrate your file to mjml 4 syntax manually then it should works

**Comment by ngarnier** [comment]
Fixed as it was related to MJML v4.1
