### ISSUE TITLE
Preview shows as blank in atom 1.47 for Mac

### ISSUE THREAD

**Issue by bvonhalle** [mjmlio/atom-mjml-preview#23]
Ever since I upgraded Atom to 1.47 for my Mac this package stopped working. When I save, a window pops open as normal, but it is blank.

When I tried on my older computer which was still on Atom 1.44 it worked no problem.

<img width="1380" alt="Screen Shot 2020-05-22 at 11 29 16 AM" src="https://user-images.githubusercontent.com/6076595/82689077-8a834780-9c1f-11ea-8452-c7610385d152.png">

**Comment by pirple-author** [comment]
+1, same issue here. Tried uninstalling and re-installing all MJML-related packages to no avail.

Atom 1.47.0 x64

**Comment by iRyusa** [comment]
Well after investigating, it looks like we can't change webview src like that anymore https://github.com/mjmlio/atom-mjml-preview/blob/master/lib/mjml-view.js#L82

**Comment by alpscontrols** [comment]
same problem here. upgraded and lost the preview.

**Comment by n1ckc1n** [comment]
I have the same issue on Windows 10.

**Comment by iRyusa** [comment]
As the problem is pretty much confirmed and identify no need to "+1" it :( cf https://github.com/mjmlio/atom-mjml-preview/issues/23#issuecomment-633307883

**Comment by iRyusa** [comment]
Seems like Webview is now working as expected on Atom 1.48 as https://github.com/atom/atom/pull/20855 fixed the issue

**Comment by dirkdig** [comment]
Yes
