### ISSUE TITLE
Images are not rendering

### ISSUE THREAD

**Issue by pjatx** [mjmlio/atom-mjml-preview#3]
Any images I include in the template are not rendering and appear broken when they are in fact valid URLs.

**Comment by ngarnier** [comment]
Hey @pjatx, thanks for opening this issue. 

Can you please share the MJML with the URLs that is causing this issue please? This is very likely because you're using relative URLs.

**Comment by ngarnier** [comment]
hi @pjatx, haven't heard back I'm closing this but feel free to reopen if you still have an issue!
