### ISSUE TITLE
mj-wrapper doesn't appear

### ISSUE THREAD

**Issue by Comicspidey** [mjmlio/atom-mjml-preview#5]
Hello,
When I use a **mj-wrapper**, preview is empty. 

I try with this code https://mjml.io/try-it-live/components/wrapper

**Comment by ngarnier** [comment]
Hey @Comicspidey, thanks! Indeed the preview is running on v3.1.0. `mj-wrapper` was introduced in v3.3.0 which is still in beta, we'll update the plugin soon :-)

**Comment by Comicspidey** [comment]
@ngarnier thanks
It would be interesting to mention the state "beta" in the official documentation ;-)

**Comment by ngarnier** [comment]
No worries! It's mentioned in the documentation and the release names :) https://github.com/mjmlio/mjml/releases 

![](https://puu.sh/ugdRC/5fa78f95d6.png)

**Comment by Comicspidey** [comment]
Maybe I'm blind, but I don't see this mention : https://mjml.io/documentation/#mjml-wrapper ;-)

**Comment by milolucero** [comment]
Same here. I was using the documentation from the main link in the header of mjml.io, without realizing that it is for the beta and not for the stable release. That link should go to the stable release documentation, or else, avoid confusion by stating clearly which of those are beta features :)

**Comment by ngarnier** [comment]
Hey @Comicspidey & @MiloLucero, we chose to document v3.3.0 beta on the website as it's available on the try it live. Sorry it led to confusion, we'll be more careful regarding the mention of beta next time.

**Comment by ngarnier** [comment]
Fixed with [v1.3.0](https://github.com/mjmlio/atom-mjml-preview/releases/tag/v1.3.0), thanks
